# Right prompt
right_format = '$kubernetes'

# Hide gcloud account
[gcloud]
disabled = true

# Disable nodejs (fnm shim is slow)
[nodejs]
disabled = true

# Kubernetes
[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
style = 'cyan'
